### ISSUE TITLE
Incorrect Bottom Border

### ISSUE THREAD

**Issue by crazyuploader** [PiyushSuthar/github-readme-quotes#1]
![image](https://user-images.githubusercontent.com/49350241/90311058-e60a5c00-df14-11ea-978c-a979fc810667.png)

I don't know if it's by designed or it's displayed incorrectly, but would appreciate if you can fix the bottom border.

**Comment by crazyuploader** [comment]
Welp, it's fixed now somehow, thanks!

**Comment by PiyushSuthar** [comment]
Sorry @crazyuploader , I didn't respond.
It was happening because of the quote, It was too long and I had hardcoded the height and width. I'll fix it soon.
