### ISSUE TITLE
Something broke

### ISSUE THREAD

**Issue by Rademenes16** [PiyushSuthar/github-readme-quotes#10]
I'm seeing this kind of error instead of quote:

![image](https://user-images.githubusercontent.com/60035016/141677307-99ca963f-e550-4c6f-9a32-7df2ad6dbd15.png)

also in this repo readme:
![image](https://user-images.githubusercontent.com/60035016/141677348-ed709621-f36e-44d3-a967-fb10f4aab9e6.png)

**Comment by PiyushSuthar** [comment]
Looks like this stopped working.
https://github.com/PiyushSuthar/github-readme-quotes/blob/dd04412079c956b5a71c90c4e8f14a78ab9194e8/src/fetcher/fetchQuotes.js#L12

It's an easy fix, you may do a PR if you wish!

**Comment by PiyushSuthar** [comment]
The issue is resolved now.

**Comment by Rademenes16** [comment]
issue reappeared

it's worth taking a look
