### ISSUE TITLE
How to create these type of api's?

### ISSUE THREAD

**Issue by chinmay29hub** [PiyushSuthar/github-readme-quotes#11]
Can anyone tell what is the tech stack used in these project and how it is implemented? And can we implement the same thing using flask?

**Comment by PiyushSuthar** [comment]
I'm using vercel serverless functions with NodeJs for this project.
You may refer to https://vercel.com/docs/concepts/functions/supported-languages#python to learn how to use serverless functions with python.

**Comment by chinmay29hub** [comment]
> I'm using vercel serverless functions with NodeJs for this project. You may refer to https://vercel.com/docs/concepts/functions/supported-languages#python to learn how to use serverless functions with python.

Ohkay. Thanks for sharing the resources. 👍

**Comment by chinmay29hub** [comment]
> I'm using vercel serverless functions with NodeJs for this project. You may refer to https://vercel.com/docs/concepts/functions/supported-languages#python to learn how to use serverless functions with python.

I was successfully able to create a api using flask. But how you are convertingthe output(the &lt;/div&gt;) into a svg so for markdown purpose????

**Comment by PiyushSuthar** [comment]
I have put the HTML inside `ForeignObject` tag and sent it with SVG headers.

Refer this code:-
https://github.com/PiyushSuthar/github-readme-quotes/blob/2eb6a6f12d5a601de46483fdaa1e310ae0db56e8/src/renderer/type/verticalCard.js#L2-L3
