### ISSUE TITLE
Select just a set of quotes

### ISSUE THREAD

**Issue by LuisBaezN** [PiyushSuthar/github-readme-quotes#17]
I'd like to have an option to select a set of quotes. I don't like some of them, like Elon's and others.

**Comment by PiyushSuthar** [comment]
Pretty straightforward to implement. Let me know if you'd like to give a pull request.

**Comment by LuisBaezN** [comment]
I'd love to, but I'm a newbie so it will take me some time (It doesn't help that my free time is so short). So, if you like you can give me something to start and I'll do it.

Thanks for your responnse!
