### ISSUE TITLE
Enhancement: `graywhite` Theme

### ISSUE THREAD

**Issue by krakxn** [PiyushSuthar/github-readme-quotes#23]
I made a PR which adds a new theme (`graywhite`).

Additionally, one question, does `symbol` refer to the double quotes ("<quote>")?

Let me know!

Note: Feel free to close this once merged or for discussion.

**Comment by PiyushSuthar** [comment]
Yes, it's the color code for the quotes.

**Comment by krakxn** [comment]
Okay, thank you. I will close this one; refer to the PR.
