### ISSUE TITLE
Suddenly Stopped Working

### ISSUE THREAD

**Issue by Zo-Bro-23** [PiyushSuthar/github-readme-quotes#32]
The app seemed to have suddenly stopped working for me. This is what I see when I visit the repo README:
![image](https://user-images.githubusercontent.com/62234360/205211273-3899cc9b-c0ea-4d6b-b21f-35a071b7de30.png)

My GitHub Profile used to have the quote working properly, but it stopped working without me changing anything. The Network Debug tab shows 502 for that too. Is this a problem at the backend Vercel server, or is it a problem at my end? I've tried with multiple devices with multiple WiFi networks, so I doubt that. Please let me know if you're facing the same issue.

**Comment by MohamedBechirMejri** [comment]
Heroku no longer supports free plans so the [quotes api](https://programming-quotes-api.herokuapp.com/) doesn't work anymore.

[This issue](https://github.com/skolakoda/programming-quotes-api/issues/54) proposes some alternatives, I hope someone has some time to redeploy it.

**Comment by Zo-Bro-23** [comment]
Hmmm... What's a temporary alternative? I would have redeployed if it was written in Javascript, but I don't know the deployment process for C#. Can you deploy C# apps to Vercel? If so, that would be the best alternative to Heroku.

**Comment by PiyushSuthar** [comment]
An easy fix ig. 
We can use the raw Json file from their GitHub to fetch data.

Just hoping it won't slow down our execution cause there's a 10s limit.

**Comment by PiyushSuthar** [comment]
Well it's up again.

**Comment by Zo-Bro-23** [comment]
Yup!
