### ISSUE TITLE
Quotes too large

### ISSUE THREAD

**Issue by OMEGA6405** [PiyushSuthar/github-readme-quotes#33]
![Screenshot 2023-01-04 11 14 42 AM](https://user-images.githubusercontent.com/98067930/210599940-852ad5eb-9ef6-4bc2-87ce-5191d2d1ee8b.png)

How do i fix this?

**Comment by OMEGA6404** [comment]
@PiyushSuthar

**Comment by PiyushSuthar** [comment]
Well the fix is pretty easy, but I'm very occupied right now can't really do anything.

**Comment by OMEGA6405** [comment]
i fixed it: <a href="https://github.com/piyushsuthar/github-readme-quotes" target="blank"><img align="center" src="https://quotes-github-readme.vercel.app/api?type=horizontal&theme=dark" alt="https://github.com/piyushsuthar/github-readme-quotes" height="200" /></a>
