### ISSUE TITLE
dark mode color

### ISSUE THREAD

**Issue by Shoaib19** [PiyushSuthar/github-readme-quotes#34]
dark mode background color of quotes should be match with github dark mode, should not set to black

**Comment by OMEGA6405** [comment]
agreed

**Comment by OMEGA6405** [comment]
@PiyushSuthar please fix this

**Comment by Deveesh-Shetty** [comment]
There is a theme called GitHub... Ig it shld help

![Screenshot_2023-06-06-07-33-17-552_com.github.android.png](https://github.com/PiyushSuthar/github-readme-quotes/assets/89470104/e82237cc-c268-48f3-bda6-daeb3eae0df7)

**Comment by Mini-Ware** [comment]
yep! you can use the following markdown
`![github theme](https://quotes-github-readme.vercel.app/api?type=horizontal&theme=github)`

this will be how it looks like
![github theme](https://quotes-github-readme.vercel.app/api?type=horizontal&theme=github)

**Comment by Shoaib19** [comment]
thanks that worked
