### ISSUE TITLE
Default system-defined light/dark color-scheme mode

### ISSUE THREAD

**Issue by R055A** [PiyushSuthar/github-readme-quotes#35]
Would it be reasonable to implement a _default light/dark mode_ instead of just light mode with equivalent functionality to the CSS `prefers-color-scheme`? That is, remove the requirement of a user manually entering their dark (or light) mode preference without affecting remaining existing functionality. If you agree to this @PiyushSuthar, can I please be assigned to the task.

**Comment by PiyushSuthar** [comment]
I don't know if `prefers-color-scheme` works in SVG. It'll be great if you add something like `&theme=auto`.

**Comment by PiyushSuthar** [comment]
Sorry for the late reply, and I've merged you PR.

Thank you for your contribution.
