### ISSUE TITLE
Bottom border not visible

### ISSUE THREAD

**Issue by prashantgarbuja** [PiyushSuthar/github-readme-quotes#40]
![Screenshot 2023-11-02 025957](https://github.com/PiyushSuthar/github-readme-quotes/assets/10545408/63977dc1-6eef-4b2a-8c7d-a6bd45049b8e)
Hi, thank you for your generous work. I tried to include a quote but the generated quote might have exceeded the limit hence, the bottom border is not visible. But it works perfectly fine when "*type=vertical*"
Can this be fixed?

**Comment by PiyushSuthar** [comment]
I haven't found a solution for it yet, perhaps you can.

**Comment by prashantgarbuja** [comment]
I will have a look into it in my spare time. 
This issue can be closed for now.
