### ISSUE TITLE
How to deal with the quote when it includes "&" character?

### ISSUE THREAD

**Issue by KeyToLove** [PiyushSuthar/github-readme-quotes#41]
Example:
My expect quote is "A & B & C",
```
https://quotes-github-readme.vercel.app/api?type=horizontal&theme=dark&quote=A & B & C 
```
![image](https://github.com/PiyushSuthar/github-readme-quotes/assets/54970106/d57f1e3c-b50d-49fa-b85e-15e63d65bad3)

**Comment by PiyushSuthar** [comment]
You need to URL encode the text.

**Comment by KeyToLove** [comment]
> You need to URL encode the text.

I had tried encode it ,but it does’t work.
```
encodeURI('https://quotes-github-readme.vercel.app/api?type=horizontal&theme=dark&quote=A & B & C ')

// result -> https://quotes-github-readme.vercel.app/api?type=horizontal&theme=dark&quote=A%20&%20B%20&%20C%20
```

**Comment by PiyushSuthar** [comment]
you'll have to replace '&' with `%26`

**Comment by KeyToLove** [comment]
> you'll have to replace '&' with `%26`

URL: https://quotes-github-readme.vercel.app/api?type=horizontal&theme=dark&quote=A%20%26%20B%20%26%20C%20

![image](https://github.com/PiyushSuthar/github-readme-quotes/assets/54970106/d41dd42c-2fd9-4a5b-ac7b-318b952628d5)

💔

**Comment by PiyushSuthar** [comment]
Replacing `&` with `%26amp;` should work.

URL: https://quotes-github-readme.vercel.app/api?type=horizontal&theme=dark&quote=A%20%26amp;%20B%20%26amp;%20C%20

![image](https://github.com/PiyushSuthar/github-readme-quotes/assets/32237558/1030c942-9f6c-40a6-879c-9c03c1828242)
