### ISSUE TITLE
Too long quote

### ISSUE THREAD

**Issue by omekrit** [PiyushSuthar/github-readme-quotes#6]
Some quotes are too long for the card to contain. Provide some customization to the card might solve the problem.

**Comment by omekrit** [comment]
To be specific, the quote is from Ken Thompson speaking about how modern programming scares him in many respects with the following explanations for  4 - 5 sentences which is very long.

**Comment by PiyushSuthar** [comment]
hmm i guess... we can probably add a string length check. 
Do lemme know If you wanna give PR.

This needs to be refactored...
https://github.com/PiyushSuthar/github-readme-quotes/blob/74a520fd76111ae2c5ef4a1b2ce6ca032431dcdc/src/fetcher/fetchQuotes.js#L11
